# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11EuFY_sRu17wYAiX2jdBsp53yanvQsEp
"""

#app.py
from flask import Flask, jsonify, request, render_template
from flask_ngrok import run_with_ngrok
import pickle

# load model
models = pickle.load(open('model.pkl','rb'))
# app
app = Flask(__name__,template_folder='template')
run_with_ngrok(app)
@app.route('/')
def home():
    return render_template('recommendation.html')
# routes

@app.route('/pred', methods=['POST'])
def predict():
     result=request.form
     query_user_name=result["user"]
     top_neighbours,recommend_list=models(query_user_name)
     return render_template('prediction.html',prediction_text1=top_neighbours,prediction_text2=recommend_list)

if __name__ == '__main__':
    app.run()

